# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-dynamodb-autoscaler
  description: Terraform module to provision DynamoDB autoscaler
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-modules, aws, dynamodb, autoscaler, iops, table, dynamodb-table, hcl2


